### ISSUE TITLE
Some bugs at downloading dataset

### ISSUE THREAD

**Issue by WEIFZH** [jc-audet/WOODS#7]
1. Option in [Docu](https://woods.readthedocs.io/en/latest/downloading_datasets.html#direct-preprocessed-download) is not consist with paper/code, e.g, MI;
2. The code about downloading (preprocessed) datasets will raise **MissingSchema(error)** like this:
> requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

**Comment by WEIFZH** [comment]
Thank you, datasets can be downloaded automatically.

**Comment by jc-audet** [comment]
Yes indeed! Thank you for pointing out the bug in the download!

Cheers @WEIFZH !
